# Site Details
title               : "PKG.fm"
description         : "Just another Mac admin blog"
url                 : "https://pkg.fm"
logo                : "https://pkg.fm/assets/icons/pkg_fm_og.png"
baseurl             : ""
paginate            : 5

# Author
author:
  name              : "Geoff Repoli"
  avatar            :
  bio               :
  location          : Philadelphia
  github            : geoffrepoli
  instagram         : geoffrepoli
  jamfnation        : grepoli
  linkedin          : geoffrepoli
  twitter           : geoffrepoli

# Analytics
analytics:
  google:
    tracking_id     : "UA-101942283-1"

# Appearance
markdown            : kramdown
permalink           : pretty

# File Associations
exclude:
  - README.md
encoding            : "UTF-8"
locale              : "en_US"

# Kramdown
kramdown:
  highlighter       : rouge
  syntax_highlighter_opts:
    block:
      line_numbers  : false

# Sass
sass:
  sass_dir          : _sass
  style             : compressed

# Gems
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
