# Site Details
title               : "pkg.fm"
description         : "just another mac admin resource"
url                 : "https://pkg.fm"
baseurl             : ""
paginate            : 5

# Author
author:
  name              : "Geoff Repoli"
  avatar            :
  bio               :
  location          : Philadelphia
  github            : geoffrepoli
  instagram         : geoffrepoli
  jamfnation        : grepoli
  linkedin          :
  twitter           : geoffrepoli

# Analytics
analytics:
  google:
    tracking_id     : "UA-101942283-1"

# Appearance
markdown            : kramdown
permalink           : /:year-:month-:day/:title

# File Associations
exclude:
  - LICENSE
  - README.md
encoding            : "utf-8"
locale              : en

# Kramdown
kramdown:
  highlighter       : rouge
  syntax_highlighter_opts:
    block:
      line_numbers  : true

# Sass
sass:
  sass_dir          : _sass
  style             : compressed

# Gems
gems:
  - jekyll-seo-tag
  - jekyll-paginate
