# Site Details
title               : "pkg.fm"
description         : "just another mac admin resource"
url                 : "https://pkg.fm"
baseurl             : ""

# Author
author:
  name              : "Geoff Repoli"
  avatar            :
  bio               :
  location          : Philadelphia
  github            : geoffrepoli
  instagram         : geoffrepoli
  jamfnation        : grepoli
  linkedin          :
  twitter           : geoffrepoli

# Analytics
analytics:
  google:
    tracking_id     : "UA-101942283-1"

# Appearance
markdown            : kramdown
permalink           : pretty

# Navigation
nav:
  - name            : "about"
    href            : ""

# Defaults
defaults:
  -
    scope:
      path          : ""
      type          : pages
    values:
      layout        : page
  -
    scope:
      path          : ""
      type          : posts
    values:
      layout        : post

# File Associations
exclude:
  - LICENSE
  - README.md
encoding            : "utf-8"
locale              : en

# Kramdown
kramdown:
  highlighter       : rouge
  syntax_highlighter_opts:
    block:
      line_numbers  : true

# Sass
sass:
  style             : compressed

# Gems
gems:
  - jekyll-seo-tag
