# Site Details
title               : PKG.fm
description         : Just another Mac admin blog
url                 : "https://pkg.fm"
logo                : "https://pkg.fm/assets/icons/pkg_fm_og.png"
baseurl             : ""

# Author
author:
  name              : Geoff Repoli
  avatar            :
  bio               :
  location          : Philadelphia
  github            : geoffrepoli
  instagram         : geoffrepoli
  jamfnation        : grepoli
  linkedin          : geoffrepoli
  twitter           : geoffrepoli

# Analytics
analytics_id:
  google:
    tracking_id     : UA-101942283-1

# Appearance
markdown            : kramdown
permalink           : /blog/:slug/
paginate            : 5

# Localization
encoding            : UTF-8
locale              : en_US
lang                : en

# Exclusions
exclude:
  - README.md
  - .DS_Store
  - LICENSE

# Kramdown
kramdown:
  highlighter       : rouge
  syntax_highlighter_opts:
    block:
      line_numbers  : false

# Sass
sass:
  sass_dir          : _sass
  style             : compressed

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
